pipeline: pipeline.optical_character_recognition.res_only.RestorationOnlyPipeline
exp_dir: experiments/optical_character_recognition/mj/002_res-only
precision: bf16
seed: 123

model:
  res_model:
    target: model.swinir.SwinIR
    params:
      img_size: 64
      patch_size: 1
      in_chans: 3
      embed_dim: 180
      depths: [6, 6, 6, 6, 6, 6, 6, 6]
      num_heads: [6, 6, 6, 6, 6, 6, 6, 6]
      window_size: 8
      mlp_ratio: 2
      sf: 8
      img_range: 1.0
      upsampler: "nearest+conv"
      resi_connection: "1conv"
      unshuffle: True
      unshuffle_scale: 8
  ocr_model:
    target: model.naver_ocr.BasicModel
    params:
      Transformation: None
      FeatureExtraction: VGG
      SequenceModeling: BiLSTM
      Prediction: CTC
      imgH: 256
      imgW: 64
      use_rgb: true
      input_channel: 3
    target_layers: ["L14"]

dataset: configs/optical_character_recognition/mj/realesrgan_cfg.yaml

val:
  resume:
    res_model: experiments/optical_character_recognition/mj/002_res-only/checkpoints/res_model_last.pt
    ocr_model: experiments/optical_character_recognition/mj/002_res-only/checkpoints/ocr_model_last.pt
  batch_size: 512
